import React, { useEffect, useMemo, useState } from 'react'
import { createRoot } from 'react-dom/client'
import { Activity, ArrowRight, ArrowUpRight, BarChart3, CalendarDays, ChevronDown, CircleHelp, Crosshair, ExternalLink, Filter, Globe2, Layers3, Menu, Search, Shield, Swords, Target, Trophy, Users } from 'lucide-react'
import './style.css'
import { Analytics } from "@vercel/analytics/next"

type Team = { id: number; name: string }
type TeamDetail = Team & { streak?: number; roster?: Team[] }
type TeamMap = { id: number; name: string; n: number; n_wins: number }
type Player = { id: number; name: string; rank: number; k: number; d: number; swing: number; adr: number; kast: number; rating: number; N: number }
type PlayerMap = Omit<Player, 'rank' | 'name'> & { name: string }
type Ranking = Team & { rank: number; points: number }
type RankingFeed = { date: string; rankings: Ranking[]; source: string; sourceUrl: string }
type TeamMatch = { date: string; team1: string; team2: string; score1: number; score2: number; event: string; url: string }
type SideMap = { name: string; ctRoundWinPct: number; tRoundWinPct: number; pistolWinPct: number; allTimeWinPct: number; allTimeRecord: string }
type TeamFeed = { logo: string; maps: SideMap[]; matches: TeamMatch[] }
type MapPlayer = { id: number; name: string; N: number; k: number; d: number; adr: number; kast: number; rating: number; ct: { rating: number; adr: number } | null; t: { rating: number; adr: number } | null }
type MapInsight = { players: MapPlayer[]; average: { rating: number | null; adr: number | null; kast: number | null; ct: { rating: number | null; adr: number | null }; t: { rating: number | null; adr: number | null } } }
type Tab = 'Overview' | 'Teams' | 'Players' | 'Tournaments'

const mapNames = ['All maps', 'Anubis', 'Ancient', 'Dust2', 'Nuke', 'Mirage', 'Inferno', 'Train', 'Overpass', 'Cache']
const mapId: Record<string, number> = { 'All maps': 0, Anubis: 1, Ancient: 3, Dust2: 4, Nuke: 5, Mirage: 6, Inferno: 7, Train: 8, Overpass: 2, Cache: 11 }
const events = [
  { name: 'StarLadder StarSeries Fall 2026', start: '2026-09-17', end: '2026-09-20', type: 'LAN', region: 'Europe', url: 'https://www.hltv.org/events' },
  { name: 'CCT 2026 Europe Series 9', start: '2026-09-15', end: '2026-09-27', type: 'Online', region: 'Europe', url: 'https://www.hltv.org/events' },
  { name: 'Logitech G Play Connect 2026', start: '2026-09-17', end: '2026-09-23', type: 'LAN', region: 'International', url: 'https://www.hltv.org/events' },
  { name: 'NODWIN Clutch Series 12', start: '2026-09-15', end: '2026-09-28', type: 'Online', region: 'International', url: 'https://www.hltv.org/events' },
  { name: 'CROSSFIRE Season 6', start: '2026-09-15', end: '2026-10-11', type: 'Online', region: 'Europe', url: 'https://www.hltv.org/events' },
  { name: 'European Pro League Series 9', start: '2026-09-12', end: '2026-09-30', type: 'Online', region: 'Europe', url: 'https://www.hltv.org/events' },
]
const fmtDate = (date: string) => new Date(date + 'T12:00:00').toLocaleDateString('en-US', { month: 'short', day: 'numeric' })
const pct = (a: number, b: number) => b ? Math.round(a / b * 100) : 0
const initials = (name: string) => name.replace(/[^a-z0-9 ]/gi, '').split(' ').map(x => x[0]).slice(0, 2).join('').toUpperCase()
const api = async<T,>(path: string): Promise<T> => { const url = path.startsWith('/fresh/') ? '/api/' + path.slice(7) : import.meta.env.DEV ? '/api' + path : '/api/data?path=' + encodeURIComponent(path); const r = await fetch(url); if (!r.ok) throw Error(`Data source returned ${r.status}`); return r.json() }
const useData = <T,>(path: string | null, initial: T) => { const [state, setState] = useState({ path, data: initial, loading: Boolean(path), error: false }); useEffect(() => { let alive = true; if (!path) { setState({ path: null, data: initial, loading: false, error: false }); return } setState({ path, data: initial, loading: true, error: false }); api<T>(path).then(data => { if (alive) setState({ path, data, loading: false, error: false }) }).catch(() => { if (alive) setState({ path, data: initial, loading: false, error: true }) }); return () => { alive = false } }, [path]); return state.path === path ? state : { path, data: initial, loading: Boolean(path), error: false } }

function TeamMark({ name, small = false, logo }: { name: string; small?: boolean; logo?: string }) { return <span className={'team-mark ' + (small ? 'small' : '')} aria-label={`${name} logo`}><Shield size={small ? 16 : 30} />{logo && <img src={logo} alt="" loading="lazy" onError={e => { e.currentTarget.style.display = 'none' }} />}</span> }
function SectionTitle({ eyebrow, title, action }: { eyebrow: string; title: string; action?: React.ReactNode }) { return <div className="section-head"><div><div className="eyebrow">{eyebrow}</div><h2>{title}</h2></div>{action}</div> }
function Skeleton({ rows = 3 }: { rows?: number }) { return <div className="skeleton-wrap">{Array.from({ length: rows }, (_, i) => <div className="skeleton" key={i} />)}</div> }
function DataIssue() { return <div className="data-issue"><CircleHelp size={18} /><span>Stats are temporarily unavailable. Try again shortly.</span></div> }

function App() {
  const [tab, setTab] = useState<Tab>('Overview'); const [mobileOpen, setMobileOpen] = useState(false)
  const [selectedTeam, setSelectedTeam] = useState<number | null>(null); const [teamQuery, setTeamQuery] = useState(''); const [teamMap, setTeamMap] = useState<string | null>(null)
  const [selectedMap, setSelectedMap] = useState('Mirage'); const [selectedPlayer, setSelectedPlayer] = useState<number | null>(null)
  const [eventFilter, setEventFilter] = useState<'Ongoing' | 'Upcoming' | 'All'>('Ongoing')
  const rankings = useData<RankingFeed>('/fresh/rankings', { date: '', rankings: [], source: '', sourceUrl: '' })
  const logos = useData<{ logos: Record<string, string> }>('/fresh/team-feed', { logos: {} })
  const teams = useData<Team[]>('/teams/?limit=100', [])
  const detail = useData<TeamDetail>(selectedTeam ? `/teams/${selectedTeam}` : null, { id: 0, name: '' })
  const teamStats = useData<TeamMap[]>(selectedTeam ? `/teams/${selectedTeam}/stats` : null, [])
  const players = useData<Player[]>(`/players/stats?mapid=${mapId[selectedMap]}&min_played=5&limit=30`, [])
  const playerMaps = useData<PlayerMap[]>(selectedPlayer ? `/players/${selectedPlayer}/stats/maps` : '/maps/', [])
  const activeTeam = teams.data.find(t => t.id === selectedTeam)?.name || rankings.data.rankings.find(t => t.id === selectedTeam)?.name || detail.data.name || 'Choose a team'
  const teamFeed = useData<TeamFeed>(selectedTeam ? `/fresh/team-feed?name=${encodeURIComponent(activeTeam)}` : null, { logo: '', maps: [], matches: [] })
  const mapInsight = useData<MapInsight>(selectedTeam && teamMap ? `/fresh/map-insights?teamId=${selectedTeam}&mapId=${mapId[teamMap]}` : null, { players: [], average: { rating: null, adr: null, kast: null, ct: { rating: null, adr: null }, t: { rating: null, adr: null } } })
  const filteredTeams = useMemo(() => teams.data.filter(t => t.name.toLowerCase().includes(teamQuery.toLowerCase())), [teamQuery, teams.data])
  const topTeams = rankings.data.rankings.slice(0, 6)
  const currentDate = new Date().toISOString().slice(0, 10)
  const filteredEvents = events.filter(e => eventFilter === 'All' || (eventFilter === 'Ongoing' ? e.start <= currentDate && e.end >= currentDate : e.start > currentDate))
  const activeMaps = teamStats.loading || teamStats.error ? [] : teamStats.data.filter(x => x.id !== 0 && x.n > 0)
  const topMap = activeMaps.filter(x => x.n >= 3).sort((a, b) => pct(b.n_wins, b.n) - pct(a.n_wins, a.n))[0]
  const overallMapRecord = teamStats.loading || teamStats.error ? undefined : teamStats.data.find(x => x.id === 0)
  const totalMaps = overallMapRecord?.n || 0
  const selectedTeamMap = teamMap ? teamStats.data.find(m => m.name === teamMap) : undefined
  const selectedSideMap = teamFeed.data.maps.find(m => m.name.toLowerCase() === teamMap?.toLowerCase())
  const logoFor = (name: string) => logos.data.logos[name.toLowerCase()] || (name === activeTeam ? teamFeed.data.logo : '')
  const highlightPlayer = players.loading || players.error ? undefined : players.data[0]
  const selectTab = (next: Tab) => { setTab(next); setMobileOpen(false); window.scrollTo({ top: 0, behavior: 'smooth' }) }
  const chooseTeam = (id: number) => { setSelectedTeam(id); setTeamMap(null) }
  useEffect(() => { if (!selectedPlayer && players.data[0]) setSelectedPlayer(players.data[0].id) }, [players.data, selectedPlayer])
  return <div className="app-shell">
    <aside className={'sidebar ' + (mobileOpen ? 'open' : '')}>
      <div className="brand"><span className="brand-icon"><Crosshair size={24} strokeWidth={2.6} /></span><span>COUNTER<span>LINE</span><small>CS2 INTELLIGENCE</small></span></div>
      <div className="sidebar-label">WORKSPACE</div>
      <nav aria-label="Main navigation">{([['Overview', BarChart3], ['Teams', Shield], ['Players', Users], ['Tournaments', Trophy]] as const).map(([name, Icon]) => <button key={name} className={'nav-item ' + (tab === name ? 'active' : '')} onClick={() => selectTab(name)}><Icon size={18} />{name}{tab === name && <span className="nav-marker" />}</button>)}</nav>
      <div className="sidebar-bottom"><div className="sidebar-signal"><span className="signal-dot" /> DATA CONNECTION <span>ACTIVE</span></div><div className="sidebar-source">Maps by <a href="https://api.csapi.de/docs" target="_blank" rel="noreferrer">CSAPI <ExternalLink size={11} /></a> · results by <a href="https://www.cs2observer.com/results" target="_blank" rel="noreferrer">CS2Observer <ExternalLink size={11} /></a><br />Tournament calendar checked Sep 19, 2026</div></div>
    </aside>
    {mobileOpen && <button className="mobile-backdrop" onClick={() => setMobileOpen(false)} aria-label="Close menu" />}
    <main className="main">
      <header className="topbar"><button className="mobile-menu" onClick={() => setMobileOpen(true)} aria-label="Open menu"><Menu size={22} /></button><div className="breadcrumb">CS2 <span>/</span> {tab}</div><div className="topbar-right"><span className="status-pill"><span className="signal-dot" /> DATA FEED</span><span className="top-date">{new Date().toLocaleDateString('en-US', { month: 'short', day: 'numeric', year: 'numeric' })}</span></div></header>
      <div className="content">
        {tab === 'Overview' && <>
          <div className="page-intro"><div className="eyebrow lime">CURRENT FORM <span className="eyebrow-line" /></div><h1>Know the maps.<br /><em>Know the players.</em></h1><p>Explore rolling team map records and player performance. Stats are from CSAPI's recent three-month sample and may lag newly completed matches.</p></div>
          <div className="metrics-grid">
            <div className="metric-card"><div className="metric-top"><span>TEAM MAP SAMPLE</span><Layers3 size={19} /></div><div className="metric-main">{totalMaps || '—'}</div><div className="metric-foot">{activeTeam} · rolling 3 months</div></div>
            <div className="metric-card"><div className="metric-top"><span>MAP SPECIALIST</span><Target size={19} /></div><div className="metric-main">{topMap?.name || '—'}</div><div className="metric-foot">{topMap ? `${activeTeam} · ${pct(topMap.n_wins, topMap.n)}% win rate over ${topMap.n} maps` : 'Select a team to explore'}</div></div>
            <div className="metric-card"><div className="metric-top"><span>TOP {selectedMap.toUpperCase()} RATING</span><Crosshair size={19} /></div><div className="metric-main">{highlightPlayer?.name || '—'}</div><div className="metric-foot">{highlightPlayer ? `${highlightPlayer.rating.toFixed(2)} rating · ${highlightPlayer.N} maps` : 'Player leaderboard'}</div></div>
            <div className="metric-card"><div className="metric-top"><span>TEAM WIN RATE</span><Activity size={19} /></div><div className="metric-main">{overallMapRecord ? `${pct(overallMapRecord.n_wins, totalMaps)}%` : '—'}</div><div className="metric-foot">{selectedTeam ? `${activeTeam} · ${totalMaps} maps sampled` : 'Select a team to explore'}</div></div>
          </div>
          <div className="overview-grid stats-first">
            <section className="panel">
              <SectionTitle eyebrow="TEAM FORM · ROLLING 3 MONTHS" title={selectedTeam ? `${activeTeam} map pool` : 'Choose a team'} action={<label className="select-label"><Shield size={16} /><select aria-label="Choose team for map pool" value={selectedTeam ?? ''} onChange={e => chooseTeam(Number(e.target.value))}><option value="" disabled>Select team</option>{teams.data.map(t => <option key={t.id} value={t.id}>{t.name}</option>)}</select><ChevronDown size={16} /></label>} />
              {!selectedTeam ? <div className="empty selection-prompt">Select a team to inspect its map pool.</div> : teamStats.loading ? <Skeleton rows={6} /> : teamStats.error ? <DataIssue /> : <div className="map-list">{activeMaps.sort((a, b) => b.n - a.n).slice(0, 6).map(m => <button key={m.id} className="map-row" onClick={() => { setTeamMap(m.name); selectTab('Teams') }}><span className="map-icon"><Layers3 size={16} /></span><span className="map-name">{m.name}</span><span className="map-games">{m.n} maps</span><span className="map-bar"><i style={{ width: `${pct(m.n_wins, m.n)}%` }} /></span><strong>{pct(m.n_wins, m.n)}%</strong><ArrowRight size={16} /></button>)}</div>}
              <div className="panel-note stat-note"><span>Win rate uses CSAPI's rolling sample.</span>{selectedTeam && <button className="text-action" onClick={() => selectTab('Teams')}>Full profile <ArrowRight size={15} /></button>}</div>
            </section>
            <section className="panel"><div className="board-head"><SectionTitle eyebrow="PLAYER FORM · MINIMUM 5 MAPS" title="Map leaders" /><label className="select-label"><Filter size={16} /><select aria-label="Choose map for leaders" value={selectedMap} onChange={e => { setSelectedMap(e.target.value); setSelectedPlayer(null) }}>{mapNames.map(m => <option key={m}>{m}</option>)}</select><ChevronDown size={16} /></label></div>{players.loading ? <Skeleton rows={6} /> : players.error ? <DataIssue /> : <div className="overview-players">{players.data.slice(0, 6).map((p, i) => <button key={p.id} className="overview-player-row" onClick={() => { setSelectedPlayer(p.id); selectTab('Players') }}><span className="rank-num">{String(i + 1).padStart(2, '0')}</span><span className="avatar">{initials(p.name)}</span><span className="overview-player-name">{p.name}<small>{p.N} maps · {p.adr.toFixed(1)} ADR</small></span><strong>{p.rating.toFixed(2)}</strong><ArrowRight size={16} /></button>)}</div>}<div className="panel-note">Rating and ADR from CSAPI's rolling three-month map sample.</div></section>
          </div>
          <section className="feature-banner"><div className="feature-graphic"><div className="radar radar-one" /><div className="radar radar-two" /><Crosshair size={65} /></div><div><div className="eyebrow lime">EXPLORE THE DETAILS</div><h2>Every map tells a story.</h2><p>Compare team win rates and discover which players own each battleground.</p></div><button onClick={() => selectTab('Teams')}>Analyze maps <ArrowRight size={17} /></button></section>
          <section className="panel rankings-panel secondary-overview"><SectionTitle eyebrow="VALVE REGIONAL STANDINGS · GLOBAL" title="Global ladder" action={rankings.data.sourceUrl && <a className="text-action" href={rankings.data.sourceUrl} target="_blank" rel="noreferrer">Official standings <ExternalLink size={15} /></a>} />{rankings.loading ? <Skeleton rows={4} /> : rankings.error ? <DataIssue /> : <div className="ranking-list">{topTeams.slice(0, 6).map(t => <button key={t.rank} className="ranking-row" disabled={!t.id} onClick={() => { chooseTeam(t.id); selectTab('Teams') }}><span className="rank-num">{String(t.rank).padStart(2, '0')}</span><TeamMark name={t.name} logo={logoFor(t.name)} small /><span className="ranking-name">{t.name}</span><span className="ranking-points">{t.points.toLocaleString()} <small>VRS PTS</small></span><ArrowRight size={16} /></button>)}</div>}<div className="panel-note">Source: <a href={rankings.data.sourceUrl || 'https://github.com/ValveSoftware/counter-strike_regional_standings'} target="_blank" rel="noreferrer">Valve's published Global Standings</a> · Snapshot {rankings.data.date || 'unavailable'}</div></section>
        </>}
        {tab === 'Teams' && <><div className="page-heading"><div><div className="eyebrow lime">THE TEAM ROOM</div><h1>Team <em>map stats.</em></h1><p>Choose a team, then open a map for its side splits and roster performance.</p></div><div className="asof">MAP STATS: CSAPI <span className="signal-dot" /></div></div>
          <div className="teams-layout"><section className="panel team-selector"><SectionTitle eyebrow="DIRECTORY" title="Select a team" /><label className="searchbox"><Search size={17} /><input value={teamQuery} onChange={e => setTeamQuery(e.target.value)} placeholder="Search teams..." /></label><div className="team-options">{teams.loading ? <Skeleton rows={8} /> : teams.error ? <DataIssue /> : filteredTeams.length ? filteredTeams.map(t => <button key={t.id} className={'team-option ' + (selectedTeam === t.id ? 'selected' : '')} onClick={() => chooseTeam(t.id)}><TeamMark name={t.name} logo={logoFor(t.name)} small /><span>{t.name}</span><ArrowRight size={15} /></button>) : <div className="empty">No teams found.</div>}</div></section>
            <div className="team-content">{!selectedTeam ? <section className="panel team-empty"><Shield size={34} /><h2>Choose a team</h2><p>Its map pool, roster, map breakdowns, and match history will appear here.</p></section> : <>
              <section className="team-hero panel"><div className="team-hero-main"><TeamMark name={activeTeam} logo={logoFor(activeTeam)} /><div><div className="eyebrow">TEAM PROFILE</div><h2>{activeTeam}</h2><p>{detail.loading ? 'Loading roster…' : `${detail.data.roster?.length || 0} players on current roster`} · rolling map stats</p></div></div><div className="team-hero-rank">{rankings.data.rankings.find(x => x.id === selectedTeam)?.rank ? <><span>VALVE VRS · {rankings.data.date}</span><strong>#{rankings.data.rankings.find(x => x.id === selectedTeam)?.rank}</strong></> : <><span>MAP RECORD</span><strong>{overallMapRecord ? `${overallMapRecord.n_wins}–${overallMapRecord.n - overallMapRecord.n_wins}` : '—'}</strong></>}</div></section>
              <section className="panel map-panel"><SectionTitle eyebrow="MAP POOL · CSAPI" title="Performance by map" action={<span className="muted-small">Rolling 3 months · click a map</span>} />{teamStats.loading ? <Skeleton rows={7} /> : teamStats.error ? <DataIssue /> : <div className="map-list">{activeMaps.sort((a, b) => b.n - a.n).map(m => <button key={m.id} className={'map-row ' + (teamMap === m.name ? 'chosen' : '')} onClick={() => setTeamMap(m.name)} aria-expanded={teamMap === m.name}><span className="map-icon"><Layers3 size={16} /></span><span className="map-name">{m.name}</span><span className="map-games">{m.n} maps</span><span className="map-bar"><i style={{ width: `${pct(m.n_wins, m.n)}%` }} /></span><strong>{pct(m.n_wins, m.n)}%</strong><ArrowRight size={16} /></button>)}</div>}</section>
              {teamMap && selectedTeamMap && <section className="panel map-breakdown"><SectionTitle eyebrow="SELECTED MAP" title={`${teamMap} breakdown`} action={<span className="muted-small">{selectedTeamMap.n_wins}W – {selectedTeamMap.n - selectedTeamMap.n_wins}L · CSAPI rolling 3 months</span>} />
                <div className="map-detail-grid">
                  <div className="detail-stat"><span>CT ROUND WIN</span><strong>{selectedSideMap ? `${selectedSideMap.ctRoundWinPct}%` : '—'}</strong><small>CS2Observer · all time</small></div>
                  <div className="detail-stat"><span>T ROUND WIN</span><strong>{selectedSideMap ? `${selectedSideMap.tRoundWinPct}%` : '—'}</strong><small>CS2Observer · all time</small></div>
                  <div className="detail-stat"><span>PISTOL ROUND WIN</span><strong>{selectedSideMap ? `${selectedSideMap.pistolWinPct}%` : '—'}</strong><small>CS2Observer · all time</small></div>
                  <div className="detail-stat"><span>ROSTER RATING</span><strong>{mapInsight.data.average.rating?.toFixed(2) || '—'}</strong><small>CSAPI · rolling 3 months</small></div>
                  <div className="detail-stat"><span>ROSTER ADR</span><strong>{mapInsight.data.average.adr?.toFixed(1) || '—'}</strong><small>CSAPI · rolling 3 months</small></div>
                  <div className="detail-stat"><span>ROSTER KAST</span><strong>{mapInsight.data.average.kast != null ? `${mapInsight.data.average.kast.toFixed(1)}%` : '—'}</strong><small>CSAPI · rolling 3 months</small></div>
                </div>
                {mapInsight.loading ? <Skeleton rows={4} /> : mapInsight.error ? <DataIssue /> : <><div className="side-rating"><span>Current roster side rating</span><strong>CT {mapInsight.data.average.ct.rating?.toFixed(2) || '—'}</strong><strong>T {mapInsight.data.average.t.rating?.toFixed(2) || '—'}</strong><small>Average player rating by side · CSAPI rolling 3 months</small></div><div className="table-scroll"><table><thead><tr><th>PLAYER</th><th>MAPS</th><th>K / D</th><th>ADR</th><th>KAST</th><th>RATING</th><th>CT RATING</th><th>T RATING</th></tr></thead><tbody>{mapInsight.data.players.map(p => <tr key={p.id}><td className="player-name"><span className="avatar">{initials(p.name)}</span><strong>{p.name}</strong></td><td>{p.N}</td><td>{p.k.toFixed(1)} / {p.d.toFixed(1)}</td><td>{p.adr.toFixed(1)}</td><td>{p.kast.toFixed(1)}%</td><td className="rating">{p.rating.toFixed(2)}</td><td>{p.ct?.rating.toFixed(2) || '—'}</td><td>{p.t?.rating.toFixed(2) || '—'}</td></tr>)}</tbody></table>{!mapInsight.data.players.length && <div className="empty">No current roster stats for this map.</div>}</div></>}
                <div className="panel-note">Utility usage is unavailable from these feeds, so it is left unreported. CT/T round wins use CS2Observer's all-time sample; player stats use CSAPI's rolling sample.</div>
              </section>}
              <section className="panel roster-panel"><SectionTitle eyebrow="FIVE IN THE SERVER" title="Current roster" />{detail.loading ? <Skeleton rows={5} /> : detail.error ? <DataIssue /> : <div className="roster-grid">{detail.data.roster?.map((p, i) => <div key={p.id} className="roster-player"><span>{String(i + 1).padStart(2, '0')}</span><strong>{p.name}</strong><button onClick={() => { setSelectedPlayer(p.id); selectTab('Players') }} aria-label={`View ${p.name} stats`}><ArrowUpRight size={17} /></button></div>)}</div>}</section>
              <section className="panel team-matches"><SectionTitle eyebrow="TEAM MATCH HISTORY" title="Recent matches" action={<a className="text-action" href={`https://www.cs2observer.com/team/${encodeURIComponent(activeTeam)}`} target="_blank" rel="noreferrer">Source <ExternalLink size={15} /></a>} />{teamFeed.loading ? <Skeleton rows={5} /> : teamFeed.error ? <DataIssue /> : teamFeed.data.matches.length ? <div className="match-list">{teamFeed.data.matches.map(m => <a className="match-row" key={m.url} href={m.url} target="_blank" rel="noreferrer"><span className="match-date">{fmtDate(m.date)}</span><div className="match-teams"><span className={m.score1 > m.score2 ? 'winner' : ''}>{m.team1}</span><strong>{m.score1} : {m.score2}</strong><span className={m.score2 > m.score1 ? 'winner' : ''}>{m.team2}</span></div><span className="match-event" title={m.event}>{m.event}</span></a>)}</div> : <div className="empty">No recent matches available for this team.</div>}<div className="panel-note">Match history via CS2Observer · dates shown per match</div></section>
            </>}</div></div>
        </>}
        {tab === 'Players' && <><div className="page-heading"><div><div className="eyebrow lime">PLAYER INTELLIGENCE</div><h1>Map <em>specialists.</em></h1><p>Find the players performing on each map, then inspect their full map profile.</p></div><div className="asof">MINIMUM 5 MAPS <span className="signal-dot" /></div></div>
          <section className="panel player-board"><div className="board-head"><SectionTitle eyebrow="PER-MAP LEADERBOARD" title="Player rankings" /><label className="select-label"><Filter size={16} /><select value={selectedMap} onChange={e => { setSelectedMap(e.target.value); setSelectedPlayer(null) }}>{mapNames.map(m => <option key={m}>{m}</option>)}</select><ChevronDown size={16} /></label></div><div className="table-scroll"><table><thead><tr><th>RANK</th><th>PLAYER</th><th>MAPS</th><th>K / D</th><th>ADR</th><th>KAST</th><th>RATING</th><th></th></tr></thead><tbody>{players.data.map((p, i) => <tr key={p.id} className={selectedPlayer === p.id ? 'selected' : ''} onClick={() => setSelectedPlayer(p.id)}><td className="rank-num">{String(i + 1).padStart(2, '0')}</td><td className="player-name"><span className="avatar">{initials(p.name)}</span><strong>{p.name}</strong></td><td>{p.N}</td><td>{p.k.toFixed(0)} / {p.d.toFixed(0)}</td><td>{p.adr.toFixed(1)}</td><td>{p.kast.toFixed(1)}%</td><td className="rating">{p.rating.toFixed(2)}</td><td><ArrowRight size={15} /></td></tr>)}</tbody></table>{players.loading && <Skeleton rows={8} />} {players.error && <DataIssue />}{!players.loading && !players.error && !players.data.length && <div className="empty">No players meet the sample threshold on this map.</div>}</div><div className="panel-note">Stats reflect the source's rolling 3 month window. K/D shows total kills and deaths in the sample.</div></section>
          <section className="panel player-detail"><SectionTitle eyebrow="PLAYER PROFILE" title={players.data.find(p => p.id === selectedPlayer)?.name || detail.data.roster?.find(p => p.id === selectedPlayer)?.name || 'Select a player'} action={<span className="muted-small">Rating by map</span>} />{playerMaps.loading ? <Skeleton rows={3} /> : playerMaps.error ? <DataIssue /> : <div className="player-map-grid">{playerMaps.data.filter(m => m.N > 0).sort((a, b) => b.rating - a.rating).slice(0, 8).map(m => <div className="player-map-card" key={m.id}><div><span>{m.name}</span><small>{m.N} maps</small></div><strong>{m.rating.toFixed(2)}</strong><div className="tiny-bar"><i style={{ width: `${Math.min(100, (m.rating / 1.7) * 100)}%` }} /></div><div className="card-meta">{m.adr.toFixed(1)} ADR <span>{m.kast.toFixed(1)}% KAST</span></div></div>)}</div>}</section>
        </>}
        {tab === 'Tournaments' && <><div className="page-heading"><div><div className="eyebrow lime">THE CIRCUIT</div><h1>Tournament <em>calendar.</em></h1><p>Track events in progress and what comes next.</p></div><div className="asof">CHECKED SEP 19, 2026 <span className="signal-dot" /></div></div>
          <div className="event-controls">{(['Ongoing', 'Upcoming', 'All'] as const).map(f => <button key={f} className={eventFilter === f ? 'active' : ''} onClick={() => setEventFilter(f)}>{f}</button>)}</div><div className="event-grid">{filteredEvents.map(e => <a className="event-card panel" key={e.name} href={e.url} target="_blank" rel="noreferrer"><div className="event-card-top"><span className="event-type"><span className="signal-dot" />{e.start <= currentDate && e.end >= currentDate ? 'ONGOING' : e.start > currentDate ? 'UPCOMING' : 'ENDED'}</span><ExternalLink size={17} /></div><div className="event-icon"><Trophy size={30} /></div><h2>{e.name}</h2><div className="event-meta"><span><CalendarDays size={15} />{fmtDate(e.start)} – {fmtDate(e.end)}</span><span><Globe2 size={15} />{e.region}</span><span><Swords size={15} />{e.type}</span></div></a>)}</div>{!filteredEvents.length && <div className="empty-event"><CalendarDays size={34} /><h2>No events in this view</h2><p>The curated calendar was last checked Sep 19, 2026. Browse the current schedule at HLTV.</p><a href="https://www.hltv.org/events" target="_blank" rel="noreferrer">Open live event calendar <ExternalLink size={15} /></a></div>}<div className="calendar-note"><CircleHelp size={16} /><span>This calendar is a curated snapshot checked Sep 19, 2026. Event dates may change. Confirm schedules with <a href="https://www.hltv.org/events" target="_blank" rel="noreferrer">HLTV <ExternalLink size={12} /></a>.</span></div>
        </>}
        <footer><span>COUNTERLINE <b>•</b> Independent CS2 stats explorer</span><span>Maps: <a href="https://api.csapi.de/docs" target="_blank" rel="noreferrer">CSAPI</a> · Rankings: <a href="https://github.com/ValveSoftware/counter-strike_regional_standings" target="_blank" rel="noreferrer">Valve VRS</a> · Results: <a href="https://www.cs2observer.com/results" target="_blank" rel="noreferrer">CS2Observer</a></span></footer>
      </div>
    </main>
  </div>
}

createRoot(document.getElementById('root')!).render(<App />)
